version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: .aws/scripts/application_stop.sh
      timeout: 15
      runas: admin
  ApplicationStart:
    - location: .aws/scripts/application_start.sh
      timeout: 300
      runas: admin

